# Generated by Django 3.2.15 on 2022-10-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_person_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Название')),
                ('description', models.TextField(help_text='Описание модельки', verbose_name='Описание')),
                ('priority', models.IntegerField(db_index=True, default=1, verbose_name='приоритет сортировки')),
                ('done', models.DateTimeField(blank=True, null=True, verbose_name='выполнено')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('deleted', models.DateTimeField(auto_now=True, verbose_name='время удаления')),
            ],
            options={
                'verbose_name': 'Дела',
                'verbose_name_plural': 'Список дел',
                'ordering': ('priority', 'created'),
            },
        ),
    ]
